import type { Message, GeminiResponse, GeminiRequestBody } from '@/lib/types';

const GEMINI_API_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent';

/**
 * Converts chat messages to Gemini API format
 */
const formatMessagesForGemini = (messages: Message[]): Array<{ role: string; parts: Array<{ text: string }> }> => {
  return messages.map(message => ({
    role: message.role === 'assistant' ? 'model' : 'user',
    parts: [{ text: message.content }]
  }));
};

/**
 * Sends a message to Gemini AI and returns the response
 */
export const sendMessageToGemini = async (
  userMessage: string, 
  conversationHistory: Message[] = []
): Promise<string> => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('Gemini API key is not configured. Please add VITE_GEMINI_API_KEY to your environment variables.');
  }

  try {
    // Prepare the conversation context
    const allMessages = [
      ...conversationHistory,
      {
        id: 'temp',
        content: userMessage,
        role: 'user' as const,
        timestamp: new Date()
      }
    ];

    const requestBody: GeminiRequestBody = {
      contents: formatMessagesForGemini(allMessages),
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 8192
      },
      safetySettings: [
        {
          category: "HARM_CATEGORY_HARASSMENT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_HATE_SPEECH",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        },
        {
          category: "HARM_CATEGORY_DANGEROUS_CONTENT",
          threshold: "BLOCK_MEDIUM_AND_ABOVE"
        }
      ]
    };

    const response = await fetch(`${GEMINI_API_BASE_URL}?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => null);
      const errorMessage = errorData?.error?.message || `HTTP ${response.status}: ${response.statusText}`;
      
      // Handle specific error cases
      if (response.status === 401) {
        throw new Error('Invalid API key. Please check your Gemini API key.');
      } else if (response.status === 403) {
        throw new Error('API access forbidden. Please check your API key permissions.');
      } else if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please try again later.');
      } else if (response.status >= 500) {
        throw new Error('Gemini service is currently unavailable. Please try again later.');
      }
      
      throw new Error(errorMessage);
    }

    const data: GeminiResponse = await response.json();

    // Validate response structure
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No response generated by the AI. Please try rephrasing your message.');
    }

    const firstCandidate = data.candidates[0];
    if (!firstCandidate.content || !firstCandidate.content.parts || firstCandidate.content.parts.length === 0) {
      throw new Error('Invalid response format from AI service.');
    }

    const responseText = firstCandidate.content.parts[0].text;
    
    if (!responseText || responseText.trim() === '') {
      throw new Error('Empty response from AI. Please try again with a different message.');
    }

    return responseText.trim();

  } catch (error) {
    console.error('Error calling Gemini API:', error);
    
    // Re-throw ApiError types as-is
    if (error instanceof Error) {
      throw error;
    }
    
    // Handle network errors
    if (error instanceof TypeError && error.message.includes('fetch')) {
      throw new Error('Network error. Please check your internet connection and try again.');
    }
    
    // Fallback for unknown errors
    throw new Error('An unexpected error occurred while communicating with the AI service.');
  }
};

/**
 * Test the API connection
 */
export const testGeminiConnection = async (): Promise<boolean> => {
  try {
    await sendMessageToGemini('Hello', []);
    return true;
  } catch (error) {
    console.error('Gemini connection test failed:', error);
    return false;
  }
};