// API Configuration
export const API_CONFIG = {
  GEMINI_BASE_URL: 'https://generativelanguage.googleapis.com/v1beta/models',
  MODEL_NAME: 'gemini-2.0-flash-exp',
  TIMEOUT: 30000, // 30 seconds
} as const;

// Generation Parameters
export const GENERATION_CONFIG = {
  temperature: 0.7,
  topK: 40,
  topP: 0.95,
  maxOutputTokens: 8192,
} as const;

// Safety Settings
export const SAFETY_SETTINGS = [
  {
    category: "HARM_CATEGORY_HARASSMENT",
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    category: "HARM_CATEGORY_HATE_SPEECH", 
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    category: "HARM_CATEGORY_DANGEROUS_CONTENT",
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  }
] as const;

// UI Configuration
export const UI_CONFIG = {
  MAX_MESSAGE_LENGTH: 4000,
  AUTO_SCROLL_DELAY: 100,
  TYPING_INDICATOR_DELAY: 500,
  MAX_CONVERSATION_HISTORY: 50, // Keep last 50 messages for context
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  API_KEY_MISSING: 'Gemini API key is not configured. Please add VITE_GEMINI_API_KEY to your environment variables.',
  API_KEY_INVALID: 'Invalid API key. Please check your Gemini API key.',
  RATE_LIMIT: 'Rate limit exceeded. Please try again later.',
  NETWORK_ERROR: 'Network error. Please check your internet connection and try again.',
  SERVICE_UNAVAILABLE: 'Gemini service is currently unavailable. Please try again later.',
  EMPTY_RESPONSE: 'Empty response from AI. Please try again with a different message.',
  INVALID_RESPONSE: 'Invalid response format from AI service.',
  NO_RESPONSE: 'No response generated by the AI. Please try rephrasing your message.',
  UNKNOWN_ERROR: 'An unexpected error occurred while communicating with the AI service.',
} as const;

// Local Storage Keys
export const STORAGE_KEYS = {
  CHAT_HISTORY: 'ai_chatbot_history',
  USER_PREFERENCES: 'ai_chatbot_preferences',
  API_KEY: 'ai_chatbot_api_key', // Note: Not recommended for production
} as const;

// App Metadata
export const APP_INFO = {
  NAME: 'AI Chatbot',
  VERSION: '1.0.0',
  DESCRIPTION: 'AI-powered chatbot using Gemini 2.5 Flash Lite',
  AUTHOR: 'Your Name',
} as const;